//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EAD_CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assigned_course
    {
        public assigned_course()
        {
            this.assignments = new HashSet<assignment>();
            this.finals = new HashSet<final>();
            this.mids = new HashSet<mid>();
            this.quizs = new HashSet<quiz>();
        }
    
        public int Id { get; set; }
        public int course_id { get; set; }
        public string batch { get; set; }
        public string degree { get; set; }
        public string t_username { get; set; }
    
        public virtual batch batch1 { get; set; }
        public virtual course course { get; set; }
        public virtual degree degree1 { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<assignment> assignments { get; set; }
        public virtual ICollection<final> finals { get; set; }
        public virtual ICollection<mid> mids { get; set; }
        public virtual ICollection<quiz> quizs { get; set; }
    }
}
